/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stock;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JDialog;
import javax.swing.Timer;
/**
 *
 * @author Lesster
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
        showDate();
        showTime();
        groupButton();
        
        
        
    }
    
    public void close()
    {

        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }
    
    
    
    public void showDate()
    {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        jMenuDate.setText("||  Current Date - " + s.format(d) + "     || ");   
    }
    
    public void showTime()
    {
        new Timer(0,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                jMenuTime.setText("Current Time - " + s.format(d));    
            }
        }).start();
    }
    
    private void groupButton()
    {
        ButtonGroup bg1 = new ButtonGroup( );

        bg1.add(jRadioButtonAddUSER);
        bg1.add(jRadioButtonAddUpdateDeleteBOOK);
        bg1.add(jRadioButtonFindLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonFindLogin = new javax.swing.JRadioButton();
        jRadioButtonAddUpdateDeleteBOOK = new javax.swing.JRadioButton();
        jRadioButtonAddUSER = new javax.swing.JRadioButton();
        jRadioButtonAddUpdateDeleteSTOCK = new javax.swing.JRadioButton();
        jButtonHelp = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonEXIT = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFILE = new javax.swing.JMenu();
        jMenuItemHOME = new javax.swing.JMenuItem();
        jMenuItemLogOut = new javax.swing.JMenuItem();
        jMenuItemHelp = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemEXIT = new javax.swing.JMenuItem();
        jMenuSWITCHUSER = new javax.swing.JMenu();
        jMenuDate = new javax.swing.JMenu();
        jMenuTime = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/ADGIF.gif"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, -20, 440, 70);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/sMAINMENU.gif"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 20, 380, 80);

        jRadioButtonFindLogin.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jRadioButtonFindLogin.setText("Find people who signed-in");
        jRadioButtonFindLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFindLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonFindLogin);
        jRadioButtonFindLogin.setBounds(50, 310, 530, 30);

        jRadioButtonAddUpdateDeleteBOOK.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jRadioButtonAddUpdateDeleteBOOK.setText("Add, Update and Delete Book Information");
        jRadioButtonAddUpdateDeleteBOOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAddUpdateDeleteBOOKActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAddUpdateDeleteBOOK);
        jRadioButtonAddUpdateDeleteBOOK.setBounds(50, 190, 520, 33);

        jRadioButtonAddUSER.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jRadioButtonAddUSER.setText("Add New user");
        jRadioButtonAddUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAddUSERActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAddUSER);
        jRadioButtonAddUSER.setBounds(50, 140, 280, 33);

        jRadioButtonAddUpdateDeleteSTOCK.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jRadioButtonAddUpdateDeleteSTOCK.setText("Add, Update and Delete Stock Information");
        jRadioButtonAddUpdateDeleteSTOCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAddUpdateDeleteSTOCKActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAddUpdateDeleteSTOCK);
        jRadioButtonAddUpdateDeleteSTOCK.setBounds(50, 250, 530, 30);

        jButtonHelp.setBackground(new java.awt.Color(51, 204, 255));
        jButtonHelp.setFont(new java.awt.Font("Aharoni", 2, 18)); // NOI18N
        jButtonHelp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Button-Help-icon.png"))); // NOI18N
        jButtonHelp.setText("HELP");
        jButtonHelp.setToolTipText("Search for HELP");
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHelp);
        jButtonHelp.setBounds(20, 360, 110, 30);

        jButtonLogin.setBackground(new java.awt.Color(0, 51, 51));
        jButtonLogin.setFont(new java.awt.Font("Aharoni", 2, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Log-Out-icon.png"))); // NOI18N
        jButtonLogin.setText("Log-Out");
        jButtonLogin.setToolTipText("Click to Proceed");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin);
        jButtonLogin.setBounds(20, 400, 120, 30);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Aharoni", 2, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 370, 90, 30);

        jButtonEXIT.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEXIT.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        jButtonEXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Button-Close-icon.png"))); // NOI18N
        jButtonEXIT.setToolTipText("EXIT from the System");
        jButtonEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEXITActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEXIT);
        jButtonEXIT.setBounds(640, 0, 20, 20);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/nature.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 680, 470);

        jMenuFILE.setText("File  ||");

        jMenuItemHOME.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemHOME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/House-icon.png"))); // NOI18N
        jMenuItemHOME.setText("Home");
        jMenuItemHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHOMEActionPerformed(evt);
            }
        });
        jMenuFILE.add(jMenuItemHOME);

        jMenuItemLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Log-Out-icon.png"))); // NOI18N
        jMenuItemLogOut.setText("Log-Out");
        jMenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogOutActionPerformed(evt);
            }
        });
        jMenuFILE.add(jMenuItemLogOut);

        jMenuItemHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Button-Help-icon.png"))); // NOI18N
        jMenuItemHelp.setText("Help");
        jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpActionPerformed(evt);
            }
        });
        jMenuFILE.add(jMenuItemHelp);
        jMenuFILE.add(jSeparator1);

        jMenuItemEXIT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Button-Close-icon.png"))); // NOI18N
        jMenuItemEXIT.setText("Exit");
        jMenuItemEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEXITActionPerformed(evt);
            }
        });
        jMenuFILE.add(jMenuItemEXIT);

        jMenuBar1.add(jMenuFILE);

        jMenuSWITCHUSER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/switch-user-icon.png"))); // NOI18N
        jMenuSWITCHUSER.setText("Switch User");
        jMenuSWITCHUSER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSWITCHUSERMouseClicked(evt);
            }
        });
        jMenuSWITCHUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSWITCHUSERActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSWITCHUSER);

        jMenuDate.setText("Date");
        jMenuBar1.add(jMenuDate);

        jMenuTime.setText("Time");
        jMenuBar1.add(jMenuTime);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(675, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonFindLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFindLoginActionPerformed
        // TODO add your handling code here:
       
        close();
        FindSignIn ad = new FindSignIn();
        {
            ad.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButtonFindLoginActionPerformed

    private void jRadioButtonAddUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAddUSERActionPerformed
        // TODO add your handling code here:
        
        close();
        AddUSER add = new AddUSER();
        {
            add.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButtonAddUSERActionPerformed

    private void jRadioButtonAddUpdateDeleteBOOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAddUpdateDeleteBOOKActionPerformed
        // TODO add your handling code here:
        
        AddBook_Display ad = new AddBook_Display();
        {
            ad.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButtonAddUpdateDeleteBOOKActionPerformed

    private void jMenuItemHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHOMEActionPerformed
        // TODO add your handling code here:
        close();
        HOME SW = new HOME();
        {
            SW.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemHOMEActionPerformed

    private void jMenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogOutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Successfully LoggedOut", "NOTE",JOptionPane.INFORMATION_MESSAGE);
        close();
        LOGINS LO = new LOGINS();
        {
            LO.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemLogOutActionPerformed

    private void jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpActionPerformed
        // TODO add your handling code here:
        String msg = "<html> Since you have sucessfully Logged-in as a Admin User <br>"
        + " you can Add new User and also you can add, update, delete<br>"
        + "and search User Information, Book Information, Stock Information. <br>"
        + "In the Menu Screen you can find 4 radio buttons which <br>"
        + "will lead you as per the following : <br>"
        + "* 1st Radio button - Add New User.<br> "
        + "* 2nd Radio button - Add, Update, Delete and Search Book Information.<br> "
        + "* 3rd Radio button - Add, Update, Delete and Search Stock Information.<br>"
        + "* 4th Radio button - Find Users who Logged-in. <br> </html>";

        JOptionPane optionpane = new JOptionPane();
        optionpane.setMessage(msg);
        optionpane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        JDialog dialog=optionpane.createDialog(null, "Help");
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemHelpActionPerformed

    private void jMenuItemEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEXITActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemEXITActionPerformed

    private void jMenuSWITCHUSERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSWITCHUSERMouseClicked
        // TODO add your handling code here:
        close();
        LOGINS SW = new LOGINS();
        {
            SW.setVisible(true);
        }
    }//GEN-LAST:event_jMenuSWITCHUSERMouseClicked

    private void jMenuSWITCHUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSWITCHUSERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSWITCHUSERActionPerformed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        // TODO add your handling code here:
        String msg = "<html> Since you have sucessfully Logged-in as a Admin User <br>"
        + " you can Add new User and also you can add, update, delete<br>"
        + "and search User Information, Book Information, Stock Information. <br>"
        + "In the Menu Screen you can find 4 radio buttons which <br>"
        + "will lead you as per the following : <br>"
        + "* 1st Radio button - Add New User.<br> "
        + "* 2nd Radio button - Add, Update, Delete and Search Book Information.<br> "
        + "* 3rd Radio button - Add, Update, Delete and Search Stock Information.<br>"
        + "* 4th Radio button - Find Users who Logged-in. <br> </html>";

        JOptionPane optionpane = new JOptionPane();
        optionpane.setMessage(msg);
        optionpane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        JDialog dialog=optionpane.createDialog(null, "Help");
        dialog.setVisible(true);

    }//GEN-LAST:event_jButtonHelpActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Successfully LoggedOut", "NOTE",JOptionPane.INFORMATION_MESSAGE);
        close();
        LOGINS LO = new LOGINS();
        {
            LO.setVisible(true);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null, "Do you want to EXIT from the System ?", "NOTE", JOptionPane.YES_NO_OPTION);
        if(YesOrNo == 0)
        {
            System.exit(0);
        }
        else
        {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEXITActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonEXITActionPerformed

    private void jRadioButtonAddUpdateDeleteSTOCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAddUpdateDeleteSTOCKActionPerformed
        // TODO add your handling code here:
       
        AddStock_Display ad = new AddStock_Display();
        {
            ad.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButtonAddUpdateDeleteSTOCKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEXIT;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDate;
    private javax.swing.JMenu jMenuFILE;
    private javax.swing.JMenuItem jMenuItemEXIT;
    private javax.swing.JMenuItem jMenuItemHOME;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemLogOut;
    private javax.swing.JMenu jMenuSWITCHUSER;
    private javax.swing.JMenu jMenuTime;
    private javax.swing.JRadioButton jRadioButtonAddUSER;
    private javax.swing.JRadioButton jRadioButtonAddUpdateDeleteBOOK;
    private javax.swing.JRadioButton jRadioButtonAddUpdateDeleteSTOCK;
    private javax.swing.JRadioButton jRadioButtonFindLogin;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
